server:
  port: 8635

spring:
  profiles:
    active: dev
  application:
    name: flink-service

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/order_center
    username: root
    password: 625211234
    driver-class-name: com.mysql.cj.jdbc.Driver

#  #线程池配置
#  task:
#    pool:
#      corePoolSize: 4
#      maxPoolSize: 8
#      keepAliveSeconds: 60
#      queueCapacity: 20

#mybatis-plus:
mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath:mapper/**.xml
